// Auto-generated by locator_ai. Do not edit manually.
import type { Page } from '@playwright/test';

type SemanticKey = 'login.username' | 'login.password' | 'login.submit';

type LocatorEntry = {
  selector: string;
  confidence: number;
  fallbacks: string[];
};

export const locatorBundle: Record<SemanticKey, LocatorEntry> = {
  'login.username': {
    selector: "css=div._3BkiHun-mminuTO-Y-zXke input[type=\"text\"]",
    confidence: 0.74,
    fallbacks: ["css=form._2v60tM463fW0V7GDe92E5f input[type=\"text\"]", "css=div.ZHRZ8czyqs7NaNmv65ARI input[type=\"text\"]", "css=div._3XCnc4SuTz8V8-jXVwkt_s input[type=\"text\"]"]
  },
  'login.password': {
    selector: "css=div._3BkiHun-mminuTO-Y-zXke input[type=\"password\"]",
    confidence: 0.92,
    fallbacks: ["css=div:has-text(\"PASSWORD\") >> css=input[type=\"password\"]", "css=form._2v60tM463fW0V7GDe92E5f input[type=\"password\"]", "css=div.ZHRZ8czyqs7NaNmv65ARI input[type=\"password\"]", "css=div._3XCnc4SuTz8V8-jXVwkt_s input[type=\"password\"]"]
  },
  'login.submit': {
    selector: "css=div._16fbihk6Bi9CXuksG7_tLt button[type=\"submit\"]",
    confidence: 0.7,
    fallbacks: ["css=form._2v60tM463fW0V7GDe92E5f button[type=\"submit\"]", "css=div.ZHRZ8czyqs7NaNmv65ARI button[type=\"submit\"]", "css=div._3XCnc4SuTz8V8-jXVwkt_s button[type=\"submit\"]", "role=button[name=\"Sign in\"]"]
  }
} as const;

export function getLocator(page: Page, key: SemanticKey) {
  const entry = locatorBundle[key];
  if (!entry) {
    throw new Error('Unknown semantic key: ' + key);
  }
  return page.locator(entry.selector);
}
